esphome:
  name: ledmatrix
  #platform: ESP8266
  #board: d1_mini
  platform: ESP32
  board: wemos_d1_mini32
  
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Ledmatrix fallback AP"
    password: !secret ap_password

web_server:
  port: 80

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:
#  password: !secret ota_password

#mqtt:
#  broker: !secret mqtt_broker
#  username: !secret mqtt_username
#  password: !secret mqtt_password
#  discovery: false

globals:
  - id: timesynced
    type: bool
    initial_value: "false"
    
time:
  - platform: homeassistant
    id: homeassistant_time
  - platform: sntp
    on_time_sync:
      - globals.set:
          id: timesynced
          value: "true"

spi:
  #clk_pin: D8  # ESP8266, CLK of MAX7219
  #mosi_pin: D7 # ESP8266, MOSI of MAX7219
  clk_pin: 23  # ESP32, CLK of MAX7219
  mosi_pin: 18 # ESP32, MOSI of MAX7219

display:
  - platform: max7219digit
    #cs_pin: D6 # ESP8266, CS of MAX7219
    cs_pin: 19 # ESP32, CS of MAX7219
    num_chips: 8
    intensity: 3
    #scroll_speed: 100ms
    update_interval: 100ms
    lambda: |-
      //if (id(haindicator4).state) it.set_invert(true); else it.set_invert(false);
      it.intensity(atoi(id(habri).state.c_str()));
      if (id(my_switch).state) 
      {
        it.printf(0, 0, id(small_font), TextAlign::TOP_LEFT, "%s", id(hatxt).state.c_str());
        //it.scroll(true, 0, atoi(id(haspeed).state.c_str()), max7219digit::CONTINUOUS, 0);
        it.scroll(true, max7219digit::CONTINUOUS, atoi(id(haspeed).state.c_str()), 0, 0);
      }
      else 
      {
        it.scroll(false);
        if (id(timesynced))
          it.strftime(0, -1, id(small_font), "%H:%M:%S", id(homeassistant_time).now());
        else it.printf(0, -1, id(small_font), "--:--:--");

        if (id(wcindicator).state) it.printf(29, -1, id(small_font), TextAlign::TOP_LEFT, "È");
        
        if (id(indoor_switch).state)
          if (id(indoor_temperature).has_state())
            if (id(indoor_temperature).state == 0.0)
              it.printf(65, -1, id(small_font), TextAlign::TOP_RIGHT , "0.0°C");
            else
              it.printf(65, -1, id(small_font), TextAlign::TOP_RIGHT , "%+.1f°C", id(indoor_temperature).state);
          else it.printf(65, -1, id(small_font), TextAlign::TOP_RIGHT , "--.-°C");
        else
          if (id(weather_temperature).has_state())
            if (id(weather_temperature).state == 0.0)
              it.printf(65, -1, id(small_font), TextAlign::TOP_RIGHT , "0.0°C");
            else
              it.printf(65, -1, id(small_font), TextAlign::TOP_RIGHT , "%+.1f°C", id(weather_temperature).state);
          else it.printf(65, -1, id(small_font), TextAlign::TOP_RIGHT , "--.-°C");
        
        if (id(haindicator2).state) {
          it.line(62,6,63,7);
          it.line(59,6,60,7);
          it.line(56,6,57,7);
          it.line(53,6,54,7);
        }
        if (id(haindicator3).state) {
          it.line(0,7,1,6);
          it.line(1,6,2,7);
          it.line(1,7,2,7);
          it.line(4,7,5,6);
          it.line(5,6,6,7);
          it.line(4,7,6,7);
        }
        if (id(haindicator4).state) {
          it.line(0,7,63,7);
        }
      }

text_sensor:
  - platform: wifi_info
    ip_address:
      name: "Ledmatrix IP address"
    ssid:
      name: "Ledmatrix connected SSID"
    bssid:
      name: "Ledmatrix display connected BSSID"
  - platform: homeassistant
    name: "HA Txt"
    id: hatxt
    entity_id: input_text.ledmatrix_text
  - platform: homeassistant
    name: "HA Brightness"
    id: habri
    entity_id: input_number.ledmatrix_bri
  - platform: homeassistant
    name: "HA Scroll speed"
    id: haspeed
    entity_id: input_number.ledmatrix_speed
  - platform: homeassistant
    name: "HA Symbol"
    id: hasymbol
    entity_id: input_text.ledmatrix_symbol
    
sensor:
  - platform: wifi_signal
    name: "Ledmatrix display WiFi signal sensor"
    update_interval: 60s
  - platform: uptime
    name: "Ledmatrix display uptime sensor"
  - platform: homeassistant
    id: weather_temperature
    entity_id: sensor.outdoor_temperature
  - platform: homeassistant
    id: indoor_temperature
    entity_id: sensor.lora_indoortemperature
    
binary_sensor:
  - platform: homeassistant
    id: wcindicator
    entity_id: binary_sensor.wc_liiketunnistin_occupancy
    #entity_id: input_boolean.wc_occupancy
  - platform: homeassistant
    name: "HA indicator2"
    id: haindicator2
    entity_id: switch.ulkopistorasia
  - platform: homeassistant
    name: "HA indicator3"
    id: haindicator3
    entity_id: light.ylakerta_jarno_kattovalo
  - platform: homeassistant
    name: "HA indicator4"
    id: haindicator4
    entity_id: binary_sensor.piha_ulkorappu_liikesensori_occupancy
    
switch:
  - platform: template
    id: my_switch
    name: "my switch"
    turn_on_action:
      - switch.template.publish:
          id: my_switch
          state: ON
    turn_off_action:
      - switch.template.publish:
          id: my_switch
          state: OFF
  - platform: template
    id: indoor_switch
    name: "indoor_switch"
    turn_on_action:
      - switch.template.publish:
          id: indoor_switch
          state: ON
    turn_off_action:
      - switch.template.publish:
          id: indoor_switch
          state: OFF
          
light:
  - platform: monochromatic
    name: "Ledmatrix LED"
    output: output_led

output:
  - platform: ledc
    id: output_led
    inverted: false
    pin: 2
    
font:
  - file: "fonts/small_5x3_mcg.ttf"
    id: small_font
    size: 8
    glyphs:
    - ' '
    - '@'
    - '*'
    - '!'
    - '"'
    - '%'
    - (
    - )
    - +
    - ','
    - '-'
    - .
    - '0'
    - '1'
    - '2'
    - '3'
    - '4'
    - '5'
    - '6'
    - '7'
    - '8'
    - '9'
    - ':'
    - A
    - B
    - C
    - D
    - E
    - F
    - G
    - H
    - I
    - J
    - K
    - L
    - M
    - N
    - O
    - P
    - Q
    - R
    - S
    - T
    - U
    - V
    - W
    - X
    - Y
    - Z
    - _
    - a
    - b
    - c
    - d
    - e
    - f
    - g
    - h
    - i
    - j
    - k
    - l
    - m
    - n
    - o
    - p
    - q
    - r
    - s
    - t
    - u
    - v
    - w
    - x
    - y
    - z
    - °
    - ä
    - ö
    - å
    - Ä
    - Ö
    - Å
    - Ç
    - È

  - file: "fonts/pixelmix_mcg.ttf"
    id: normal_font
    size: 8
    glyphs:
    - ' '
    - '@'
    - '*'
    - '!'
    - '"'
    - '%'
    - (
    - )
    - +
    - ','
    - '-'
    - .
    - '0'
    - '1'
    - '2'
    - '3'
    - '4'
    - '5'
    - '6'
    - '7'
    - '8'
    - '9'
    - ':'
    - A
    - B
    - C
    - D
    - E
    - F
    - G
    - H
    - I
    - J
    - K
    - L
    - M
    - N
    - O
    - P
    - Q
    - R
    - S
    - T
    - U
    - V
    - W
    - X
    - Y
    - Z
    - _
    - a
    - b
    - c
    - d
    - e
    - f
    - g
    - h
    - i
    - j
    - k
    - l
    - m
    - n
    - o
    - p
    - q
    - r
    - s
    - t
    - u
    - v
    - w
    - x
    - y
    - z
    - °
    - ä
    - ö
    - Ä
    - Ö
